## 설치

In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.3 MB 4.7 MB/s 
     |████████████████████████████████| 7.6 MB 50.0 MB/s 
     |████████████████████████████████| 163 kB 83.3 MB/s 


In [2]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 441 kB 4.6 MB/s 
     |████████████████████████████████| 212 kB 83.6 MB/s 
     |████████████████████████████████| 115 kB 68.5 MB/s 
     |████████████████████████████████| 127 kB 78.9 MB/s 
     |████████████████████████████████| 115 kB 81.3 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [3]:
!pip install wandb -qU

     |████████████████████████████████| 1.9 MB 4.7 MB/s 
     |████████████████████████████████| 182 kB 76.3 MB/s 
     |████████████████████████████████| 166 kB 74.6 MB/s 
     |████████████████████████████████| 63 kB 1.8 MB/s 
     |████████████████████████████████| 166 kB 80.6 MB/s 
     |████████████████████████████████| 162 kB 80.1 MB/s 
     |████████████████████████████████| 162 kB 79.3 MB/s 
     |████████████████████████████████| 158 kB 76.8 MB/s 
     |████████████████████████████████| 157 kB 84.1 MB/s 
     |████████████████████████████████| 157 kB 81.0 MB/s 
     |████████████████████████████████| 157 kB 83.4 MB/s 
     |████████████████████████████████| 157 kB 81.2 MB/s 
     |████████████████████████████████| 157 kB 67.0 MB/s 
     |████████████████████████████████| 157 kB 79.8 MB/s 
     |████████████████████████████████| 157 kB 77.5 MB/s 
     |████████████████████████████████| 156 kB 83.8 MB/s 


In [4]:
!kaggle datasets download -d minjaechoi99/aihub-groom

 76% 29.0M/38.1M [00:00<00:00, 158MB/s] 
100% 38.1M/38.1M [00:00<00:00, 172MB/s]


In [5]:
!unzip /content/aihub-groom.zip

Archive:  /content/aihub-groom.zip
  inflating: data/Training/talksets-train-1.json  
  inflating: data/Training/talksets-train-2.json  
  inflating: data/Training/talksets-train-3.json  
  inflating: data/Training/talksets-train-4.json  
  inflating: data/Training/talksets-train-5.json  
  inflating: data/Validation/talksets-train-6.json  


In [30]:
import torch
import torch.optim as optim

import numpy as np
import tqdm as tqdm

from transformers import(
    AutoModel,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    default_data_collator,
    DefaultDataCollator,
    EarlyStoppingCallback,
    get_cosine_schedule_with_warmup,
    get_linear_schedule_with_warmup,
    get_constant_schedule,
    AdamW
)

In [7]:
import wandb
wandb.login()

ERROR:wandb.jupyter:Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.


<IPython.core.display.Javascript object>

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


True

## readjson

In [78]:
from pathlib import Path
import json, re
def read_aihub(path):
    path = Path(path)
    with open(path, 'rb') as f:
        print(f)
        squad_dict = json.load(f)
    texts = []
    ids = []
    for group in squad_dict:
        for passage in group['sentences']:
            id = passage['id']
            text = passage['origin_text']
            text = re.sub('#.*?#', '[UNK]', text)
            intensity = passage['intensity']
            if intensity == 1:
                continue
            if intensity < 1:
                texts.append(text)
                ids.append(id)

    return texts, ids

In [79]:
import pandas as pd

texts = []
ids = []
for i in range(1,6):
    file_path =  f'/content/data/Training/talksets-train-{i}.json'
    ttexts, iids = read_aihub(file_path)
    texts += ttexts
    ids += iids
moral_df = pd.DataFrame(list(zip(ids, texts)),
            columns =['ids', 'texts'])

<_io.BufferedReader name='/content/data/Training/talksets-train-1.json'>
<_io.BufferedReader name='/content/data/Training/talksets-train-2.json'>
<_io.BufferedReader name='/content/data/Training/talksets-train-3.json'>
<_io.BufferedReader name='/content/data/Training/talksets-train-4.json'>
<_io.BufferedReader name='/content/data/Training/talksets-train-5.json'>


In [80]:
moral_df

ids                        texts
0       615d33ea78290791e9561d5c-3          쉴드가 아니라 국가가 면제해준거야.
1       615d33fc78290791e9566c56-2                짐승입장도 들어봐야지ㅋㅋ
2       61921b89b1bee6a4bd7bdd1f-1           [UNK]이 이제 급하긴 한가보네
3       61921b89b1bee6a4bd7bdd1f-2               깐부라고 부르기까지 하다니
4       615d33f378290791e95644c2-1  어머니 간 이식 해 주기 싫어서 도망쳤다고...?
...                            ...                          ...
162943  616922089cbb21a3042d9bcd-3      와 넌 모욕죄 낼 통장 잔고가 넉넉한가봐?
162944  6152b6b7aab10bca18b8ff9f-1             바나나 먹으면 나한테 반하나?
162945  61651454ebf4829a1b39f676-3                   오죽 하면 그러겠나
162946  615fb4a1dcbfe5fa32e5ce63-2                      신경 끄세요.
162947  615fb4a1dcbfe5fa32e5ce63-3                이제라도 관리 좀 해라.

[162948 rows x 2 columns]

In [81]:
from datasets import Dataset

moral_data = Dataset.from_pandas(moral_df)

In [82]:
moral_data

Dataset({
    features: ['ids', 'texts'],
    num_rows: 162948
})

## tokenize

In [83]:
model_name = 'beomi/KcELECTRA-base-v2022'
model_version = 'groom2team/pj3_class_kcelectra/pytorch_finetuned:v8'
max_length = 128

In [84]:
import wandb
run = wandb.init()
artifact1 = run.use_artifact(model_version, type='model')
artifact_dir1 = artifact1.download()

model = AutoModelForSequenceClassification.from_pretrained(model_name)
model.load_state_dict(torch.load(artifact_dir1+'/best_model_at_end/pytorch_model.bin'))

tokenizer = AutoTokenizer.from_pretrained(model_name)

wandb: Downloading large artifact pytorch_finetuned:v8, 489.19MB. 7 files... 
wandb:   7 of 7 files downloaded.  
Done. 0:0:0.1
Some weights of the model checkpoint at beomi/KcELECTRA-base-v2022 were not used when initializing ElectraForSequenceClassification: ['discriminator_predictions.dense.bias', 'discriminator_predictions.dense.weight', 'discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense_prediction.weight']
- This IS expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ElectraForSequenceClassification were

In [85]:
def tokenizeWithoutLabel(data):
    tokenized_datas = tokenizer(
        data['texts'],
        max_length=max_length,
        padding="max_length",
        truncation="only_second"
    )
    return tokenized_datas

In [86]:
device = torch.device('cuda')
model = model.to(device)

In [87]:
def get_softmax(text):
    texts = []
    texts.append({'ids': 0, 'texts' : text})
    tokens = tokenizer.encode(text)
    for i in range(1, len(tokens) - 1):
        texts.append({'ids': i, 'texts' : tokenizer.decode(tokens[1:i] + tokens[i+1:len(tokens)-1])})
    line_data = Dataset.from_list(texts)
    print(line_data)
    line_tokenized_datasets = line_data.map(tokenizeWithoutLabel, batched=True, remove_columns=line_data.column_names)
    data_collator = DefaultDataCollator(return_tensors="pt")
    line_loader = torch.utils.data.DataLoader(line_tokenized_datasets, batch_size=len(line_tokenized_datasets),
                                            shuffle=False, collate_fn=data_collator,
                                            num_workers=0)
    for id_inputs in line_loader:
        torch.cuda.empty_cache()
        inputs = {}
        inputs['input_ids'] = id_inputs['input_ids'].to(device)
        inputs['token_type_ids'] = id_inputs['token_type_ids'].to(device)
        inputs['attention_mask'] = id_inputs['attention_mask'].to(device)
        outputs = model(**inputs)
        logits = outputs.logits
        softmax = logits.softmax(dim=-1)
        for i, prob in enumerate(softmax):
            print(prob, texts[i])
        print(text)


In [89]:
for line in moral_data:
    get_softmax(line['texts'])

Dataset({
    features: ['ids', 'texts'],
    num_rows: 9
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9700, 0.0300], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '쉴드가 아니라 국가가 면제해준거야.'}
tensor([0.9744, 0.0256], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##가 아니라 국가가 면제해준거야.'}
tensor([0.9792, 0.0208], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '쉴드 아니라 국가가 면제해준거야.'}
tensor([0.8221, 0.1779], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '쉴드가 국가가 면제해준거야.'}
tensor([0.9771, 0.0229], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '쉴드가 아니라 면제해준거야.'}
tensor([0.9478, 0.0522], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '쉴드가 아니라 국가가해준거야.'}
tensor([0.9038, 0.0962], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '쉴드가 아니라 국가가 면제거야.'}
tensor([0.9274, 0.0726], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '쉴드가 아니라 국가가 면제해준.'}
tensor([0.9593, 0.0407], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '쉴드가 아니라 국가가 면제해준거야'}
쉴드가 아니라 국

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.7589, 0.2411], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '짐승입장도 들어봐야지ㅋㅋ'}
tensor([0.9571, 0.0429], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##입장도 들어봐야지ㅋㅋ'}
tensor([0.5068, 0.4932], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '짐승도 들어봐야지ㅋㅋ'}
tensor([0.7562, 0.2438], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '짐승입장 들어봐야지ㅋㅋ'}
tensor([0.7847, 0.2153], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '짐승입장도봐야지ㅋㅋ'}
tensor([0.7014, 0.2986], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '짐승입장도 들어ㅋㅋ'}
tensor([0.9499, 0.0501], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '짐승입장도 들어봐야지'}
짐승입장도 들어봐야지ㅋㅋ
Dataset({
    features: ['ids', 'texts'],
    num_rows: 7
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9797, 0.0203], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '[UNK]이 이제 급하긴 한가보네'}
tensor([0.9932, 0.0068], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '이 이제 급하긴 한가보네'}
tensor([0.9799, 0.0201], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '[UNK] 이제 급하긴 한가보네'}
tensor([0.9852, 0.0148], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '[UNK] 이 급하긴 한가보네'}
tensor([0.9747, 0.0253], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '[UNK] 이 이제 한가보네'}
tensor([0.9683, 0.0317], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '[UNK] 이 이제 급하긴보네'}
tensor([0.9750, 0.0250], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '[UNK] 이 이제 급하긴 한가'}
[UNK]이 이제 급하긴 한가보네
Dataset({
    features: ['ids', 'texts'],
    num_rows: 7
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9704, 0.0296], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '깐부라고 부르기까지 하다니'}
tensor([0.9272, 0.0728], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##부라고 부르기까지 하다니'}
tensor([0.9235, 0.0765], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '깐라고 부르기까지 하다니'}
tensor([0.9759, 0.0241], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '깐부 부르기까지 하다니'}
tensor([0.9502, 0.0498], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '깐부라고기까지 하다니'}
tensor([0.9547, 0.0453], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '깐부라고 부르 하다니'}
tensor([0.9646, 0.0354], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '깐부라고 부르기까지'}
깐부라고 부르기까지 하다니
Dataset({
    features: ['ids', 'texts'],
    num_rows: 13
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9906, 0.0094], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '어머니 간 이식 해 주기 싫어서 도망쳤다고...?'}
tensor([0.9893, 0.0107], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '간 이식 해 주기 싫어서 도망쳤다고...?'}
tensor([0.9901, 0.0099], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '어머니 이식 해 주기 싫어서 도망쳤다고...?'}
tensor([0.6491, 0.3509], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '어머니 간 해 주기 싫어서 도망쳤다고...?'}
tensor([0.9874, 0.0126], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '어머니 간 이식 주기 싫어서 도망쳤다고...?'}
tensor([0.9911, 0.0090], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '어머니 간 이식 해 싫어서 도망쳤다고...?'}
tensor([0.9915, 0.0085], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '어머니 간 이식 해 주기 도망쳤다고...?'}
tensor([0.9877, 0.0123], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '어머니 간 이식 해 주기 싫어서다고...?'}
tensor([0.9734, 0.0266], device='cuda:0', grad_fn=<UnbindBackw

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9764, 0.0236], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '와 드디어 일 다 했다'}
tensor([0.9597, 0.0403], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '드디어 일 다 했다'}
tensor([0.9759, 0.0241], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '와 일 다 했다'}
tensor([0.9788, 0.0212], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '와 드디어 다 했다'}
tensor([0.9803, 0.0197], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '와 드디어 일 했다'}
tensor([0.9773, 0.0227], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '와 드디어 일 다'}
와 드디어 일 다 했다
Dataset({
    features: ['ids', 'texts'],
    num_rows: 5
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9976, 0.0024], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '그동안 고생 많았어'}
tensor([0.9977, 0.0023], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '고생 많았어'}
tensor([0.9953, 0.0047], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '그동안 많았어'}
tensor([0.9935, 0.0065], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '그동안 고생어'}
tensor([0.9966, 0.0034], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '그동안 고생 많았'}
그동안 고생 많았어
Dataset({
    features: ['ids', 'texts'],
    num_rows: 9
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9318, 0.0682], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '고생한 기념으로 내가 저녁 사 줄게'}
tensor([0.9076, 0.0924], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##한 기념으로 내가 저녁 사 줄게'}
tensor([0.9386, 0.0614], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '고생 기념으로 내가 저녁 사 줄게'}
tensor([0.9532, 0.0468], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '고생한으로 내가 저녁 사 줄게'}
tensor([0.9670, 0.0330], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '고생한 기념 내가 저녁 사 줄게'}
tensor([0.9378, 0.0622], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '고생한 기념으로 저녁 사 줄게'}
tensor([0.9017, 0.0983], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '고생한 기념으로 내가 사 줄게'}
tensor([0.8823, 0.1177], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '고생한 기념으로 내가 저녁 줄게'}
tensor([0.9491, 0.0509], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '고생한 기념으로 내가 저녁 사'}
고생한 기념으로 

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9973, 0.0027], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '이번에 [UNK] 유뷰트 봤는데, 3차선에서 역주행하는 차가 있데'}
tensor([0.9968, 0.0032], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '[UNK] 유뷰트 봤는데, 3차선에서 역주행하는 차가 있데'}
tensor([0.9974, 0.0026], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '이번에 유뷰트 봤는데, 3차선에서 역주행하는 차가 있데'}
tensor([0.9966, 0.0034], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '이번에 [UNK]뷰트 봤는데, 3차선에서 역주행하는 차가 있데'}
tensor([0.9968, 0.0032], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '이번에 [UNK] 유트 봤는데, 3차선에서 역주행하는 차가 있데'}
tensor([0.9972, 0.0028], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '이번에 [UNK] 유뷰 봤는데, 3차선에서 역주행하는 차가 있데'}
tensor([0.9972, 0.0028], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '이번에 [UNK] 유뷰트, 3차선에서 역주행하는 차가 있데'}
tensor([0.9974, 0.0026], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '이번에 [UNK] 유뷰트 봤는데 3차선에서 역

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9600, 0.0400], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '한 번 보여줘봐'}
tensor([0.9405, 0.0595], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '번 보여줘봐'}
tensor([0.9428, 0.0572], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '한 보여줘봐'}
tensor([0.9879, 0.0121], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '한 번봐'}
tensor([0.8558, 0.1442], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '한 번 보여줘'}
한 번 보여줘봐
Dataset({
    features: ['ids', 'texts'],
    num_rows: 11
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.8709, 0.1291], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '저렇게 운전해 놓고 내려서 자기가 화를 내는거냐?'}
tensor([0.9575, 0.0425], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '운전해 놓고 내려서 자기가 화를 내는거냐?'}
tensor([0.8925, 0.1075], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '저렇게해 놓고 내려서 자기가 화를 내는거냐?'}
tensor([0.9426, 0.0574], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '저렇게 운전 놓고 내려서 자기가 화를 내는거냐?'}
tensor([0.9526, 0.0474], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '저렇게 운전해 내려서 자기가 화를 내는거냐?'}
tensor([0.8636, 0.1364], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '저렇게 운전해 놓고 자기가 화를 내는거냐?'}
tensor([0.8365, 0.1635], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '저렇게 운전해 놓고 내려서 화를 내는거냐?'}
tensor([0.8525, 0.1475], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '저렇게 운전해 놓고 내려서 자기가 내는거냐?'}
tensor([0.7956, 0.2044], device='cuda:0', grad_fn=<UnbindBackw

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9904, 0.0096], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '저런 대응은 정말 이해가 안되지?'}
tensor([0.9875, 0.0125], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '대응은 정말 이해가 안되지?'}
tensor([0.9890, 0.0110], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '저런은 정말 이해가 안되지?'}
tensor([0.9933, 0.0067], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '저런 대응 정말 이해가 안되지?'}
tensor([0.9918, 0.0082], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '저런 대응은 이해가 안되지?'}
tensor([0.9887, 0.0113], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '저런 대응은 정말 안되지?'}
tensor([0.9890, 0.0110], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '저런 대응은 정말 이해가?'}
tensor([0.9857, 0.0143], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '저런 대응은 정말 이해가 안되지'}
저런 대응은 정말 이해가 안되지?
Dataset({
    features: ['ids', 'texts'],
    num_rows: 8
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.8766, 0.1234], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '[UNK]라고 다 같은 [UNK]가 아니야'}
tensor([0.8635, 0.1365], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '라고 다 같은 [UNK] 가 아니야'}
tensor([0.8915, 0.1085], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '[UNK] 다 같은 [UNK] 가 아니야'}
tensor([0.9291, 0.0709], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '[UNK] 라고 같은 [UNK] 가 아니야'}
tensor([0.9418, 0.0582], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '[UNK] 라고 다 [UNK] 가 아니야'}
tensor([0.9241, 0.0759], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '[UNK] 라고 다 같은 가 아니야'}
tensor([0.9110, 0.0890], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '[UNK] 라고 다 같은 [UNK] 아니야'}
tensor([0.7627, 0.2373], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '[UNK] 라고 다 같은 [UNK] 가'}
[UNK]라고 다 같은 [UNK]가 아니야
Dataset({
    features: ['ids', 'texts'],
    num_rows: 10
}

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9872, 0.0128], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '요새는 온갖 방법으로 다 들어와서 수준이 천차만별이래'}
tensor([0.9736, 0.0264], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##는 온갖 방법으로 다 들어와서 수준이 천차만별이래'}
tensor([0.9871, 0.0129], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '요새 온갖 방법으로 다 들어와서 수준이 천차만별이래'}
tensor([0.9952, 0.0048], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '요새는 방법으로 다 들어와서 수준이 천차만별이래'}
tensor([0.9725, 0.0275], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '요새는 온갖 다 들어와서 수준이 천차만별이래'}
tensor([0.9899, 0.0101], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '요새는 온갖 방법으로 들어와서 수준이 천차만별이래'}
tensor([0.9936, 0.0064], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '요새는 온갖 방법으로 다 수준이 천차만별이래'}
tensor([0.9949, 0.0051], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '요새는 온갖 방법으로 다 들어와서 천차만별이래'}
tensor([0.8703, 0.1297], device='cuda:0', gr

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9667, 0.0333], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '그래? 그래도 [UNK]인데 머리는 좋겠지'}
tensor([0.9715, 0.0285], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '? 그래도 [UNK] 인데 머리는 좋겠지'}
tensor([0.9611, 0.0389], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '그래 그래도 [UNK] 인데 머리는 좋겠지'}
tensor([0.9618, 0.0382], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '그래? [UNK] 인데 머리는 좋겠지'}
tensor([0.9792, 0.0208], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '그래? 그래도 인데 머리는 좋겠지'}
tensor([0.9715, 0.0285], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '그래? 그래도 [UNK] 머리는 좋겠지'}
tensor([0.9844, 0.0156], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '그래? 그래도 [UNK] 인데 좋겠지'}
tensor([0.9334, 0.0666], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '그래? 그래도 [UNK] 인데 머리는지'}
tensor([0.9361, 0.0639], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts':

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9567, 0.0433], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '아직 대학에 적응을 못한 거 아냐?'}
tensor([0.9256, 0.0744], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '대학에 적응을 못한 거 아냐?'}
tensor([0.9566, 0.0434], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '아직에 적응을 못한 거 아냐?'}
tensor([0.9637, 0.0363], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '아직 대학 적응을 못한 거 아냐?'}
tensor([0.8167, 0.1833], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '아직 대학에을 못한 거 아냐?'}
tensor([0.9628, 0.0372], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '아직 대학에 적응 못한 거 아냐?'}
tensor([0.9833, 0.0167], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '아직 대학에 적응을 거 아냐?'}
tensor([0.9474, 0.0526], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '아직 대학에 적응을 못한 아냐?'}
tensor([0.9806, 0.0194], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '아직 대학에 적응을 못한 거?'}
tensor([0.9

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9500, 0.0500], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '의사들은 좋겠다 돈 많이 벌어서'}
tensor([0.9453, 0.0547], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '좋겠다 돈 많이 벌어서'}
tensor([0.9938, 0.0062], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '의사들은 돈 많이 벌어서'}
tensor([0.9341, 0.0659], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '의사들은 좋겠다 많이 벌어서'}
tensor([0.9273, 0.0727], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '의사들은 좋겠다 돈 벌어서'}
tensor([0.9586, 0.0414], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '의사들은 좋겠다 돈 많이'}
의사들은 좋겠다 돈 많이 벌어서
Dataset({
    features: ['ids', 'texts'],
    num_rows: 7
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9851, 0.0149], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '근데 병원에 있으면 너무 우울할듯'}
tensor([0.9881, 0.0119], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '병원에 있으면 너무 우울할듯'}
tensor([0.9720, 0.0280], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '근데 있으면 너무 우울할듯'}
tensor([0.9855, 0.0145], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '근데 병원에 너무 우울할듯'}
tensor([0.9731, 0.0269], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '근데 병원에 있으면 우울할듯'}
tensor([0.9525, 0.0475], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '근데 병원에 있으면 너무할듯'}
tensor([0.9895, 0.0105], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '근데 병원에 있으면 너무 우울'}
근데 병원에 있으면 너무 우울할듯
Dataset({
    features: ['ids', 'texts'],
    num_rows: 13
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.4555, 0.5445], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '1년 반 동안 한 거라곤 세금 퍼주기랑 거리두기밖에 없네'}
tensor([0.3952, 0.6048], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '반 동안 한 거라곤 세금 퍼주기랑 거리두기밖에 없네'}
tensor([0.4776, 0.5224], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '1년 동안 한 거라곤 세금 퍼주기랑 거리두기밖에 없네'}
tensor([0.5188, 0.4812], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '1년 반 한 거라곤 세금 퍼주기랑 거리두기밖에 없네'}
tensor([0.5370, 0.4630], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '1년 반 동안 거라곤 세금 퍼주기랑 거리두기밖에 없네'}
tensor([0.5183, 0.4817], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '1년 반 동안 한곤 세금 퍼주기랑 거리두기밖에 없네'}
tensor([0.5105, 0.4895], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '1년 반 동안 한 거라 세금 퍼주기랑 거리두기밖에 없네'}
tensor([0.5348, 0.4652], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '1년 반 동안 한 거라곤 퍼주기랑 거리두기밖에 없네'}
tensor([0.6590, 0.3410], 

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.8158, 0.1842], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '지금껏 포퓰리즘 정책밖에 없음'}
tensor([0.7298, 0.2702], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '포퓰리즘 정책밖에 없음'}
tensor([0.9698, 0.0302], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '지금껏 정책밖에 없음'}
tensor([0.8384, 0.1616], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '지금껏 포퓰리즘밖에 없음'}
tensor([0.9881, 0.0119], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '지금껏 포퓰리즘 정책 없음'}
tensor([0.8062, 0.1938], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '지금껏 포퓰리즘 정책밖에'}
지금껏 포퓰리즘 정책밖에 없음
Dataset({
    features: ['ids', 'texts'],
    num_rows: 5
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9759, 0.0241], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '[UNK]이 당선 될듯'}
tensor([0.9857, 0.0143], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '이 당선 될듯'}
tensor([0.9748, 0.0252], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '[UNK] 당선 될듯'}
tensor([0.8806, 0.1194], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '[UNK] 이 될듯'}
tensor([0.9604, 0.0396], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '[UNK] 이 당선'}
[UNK]이 당선 될듯
Dataset({
    features: ['ids', 'texts'],
    num_rows: 8
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9949, 0.0051], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '여론조사도 [UNK]이 높더라.'}
tensor([0.9210, 0.0790], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##도 [UNK] 이 높더라.'}
tensor([0.9967, 0.0033], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '여론조사 [UNK] 이 높더라.'}
tensor([0.9967, 0.0033], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '여론조사도 이 높더라.'}
tensor([0.9946, 0.0054], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '여론조사도 [UNK] 높더라.'}
tensor([0.9804, 0.0196], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '여론조사도 [UNK] 이더라.'}
tensor([0.9809, 0.0191], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '여론조사도 [UNK] 이 높.'}
tensor([0.9948, 0.0052], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '여론조사도 [UNK] 이 높더라'}
여론조사도 [UNK]이 높더라.
Dataset({
    features: ['ids', 'texts'],
    num_rows: 7
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9817, 0.0183], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '6070은 [UNK]이 더 높아'}
tensor([0.9253, 0.0747], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##은 [UNK] 이 더 높아'}
tensor([0.9709, 0.0291], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '6070 [UNK] 이 더 높아'}
tensor([0.9829, 0.0171], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '6070은 이 더 높아'}
tensor([0.9780, 0.0220], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '6070은 [UNK] 더 높아'}
tensor([0.9660, 0.0340], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '6070은 [UNK] 이 높아'}
tensor([0.7365, 0.2635], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '6070은 [UNK] 이 더'}
6070은 [UNK]이 더 높아
Dataset({
    features: ['ids', 'texts'],
    num_rows: 8
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.8804, 0.1196], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '뭐라하냐 백세시대에 ㅋㅋㅋ'}
tensor([0.6766, 0.3234], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##하냐 백세시대에 ㅋㅋㅋ'}
tensor([0.8775, 0.1225], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '뭐라 백세시대에 ㅋㅋㅋ'}
tensor([0.9067, 0.0933], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '뭐라하냐세시대에 ㅋㅋㅋ'}
tensor([0.8642, 0.1358], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '뭐라하냐 백시대에 ㅋㅋㅋ'}
tensor([0.8596, 0.1404], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '뭐라하냐 백세 ㅋㅋㅋ'}
tensor([0.9136, 0.0864], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '뭐라하냐 백세시대에ㅋ'}
tensor([0.9190, 0.0810], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '뭐라하냐 백세시대에 ㅋㅋ'}
뭐라하냐 백세시대에 ㅋㅋㅋ
Dataset({
    features: ['ids', 'texts'],
    num_rows: 6
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9969, 0.0031], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '난 그래도 좋은 사람이였구나'}
tensor([0.9955, 0.0045], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '그래도 좋은 사람이였구나'}
tensor([0.9972, 0.0028], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '난 좋은 사람이였구나'}
tensor([0.9827, 0.0173], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '난 그래도 사람이였구나'}
tensor([0.9952, 0.0048], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '난 그래도 좋은였구나'}
tensor([0.9971, 0.0029], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '난 그래도 좋은 사람이'}
난 그래도 좋은 사람이였구나
Dataset({
    features: ['ids', 'texts'],
    num_rows: 11
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9974, 0.0026], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '쟤 이번에 트레이너 회원수 랭킹 1위 찍었다며?'}
tensor([0.9979, 0.0021], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '이번에 트레이너 회원수 랭킹 1위 찍었다며?'}
tensor([0.9965, 0.0035], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '쟤 트레이너 회원수 랭킹 1위 찍었다며?'}
tensor([0.9973, 0.0027], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '쟤 이번에 회원수 랭킹 1위 찍었다며?'}
tensor([0.9978, 0.0022], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '쟤 이번에 트레이너수 랭킹 1위 찍었다며?'}
tensor([0.9976, 0.0024], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '쟤 이번에 트레이너 회원 랭킹 1위 찍었다며?'}
tensor([0.9975, 0.0025], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '쟤 이번에 트레이너 회원수 1위 찍었다며?'}
tensor([0.9971, 0.0029], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '쟤 이번에 트레이너 회원수 랭킹 찍었다며?'}
tensor([0.9973, 0.0027], device='cuda:0', grad_fn=<UnbindBackward0>) 

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9906, 0.0094], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '야 그래도 실력이 있으니 가능한거 아니겠어?'}
tensor([0.9913, 0.0087], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '그래도 실력이 있으니 가능한거 아니겠어?'}
tensor([0.9878, 0.0122], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '야 실력이 있으니 가능한거 아니겠어?'}
tensor([0.9743, 0.0257], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '야 그래도 있으니 가능한거 아니겠어?'}
tensor([0.9906, 0.0094], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '야 그래도 실력이 가능한거 아니겠어?'}
tensor([0.9911, 0.0089], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '야 그래도 실력이 있으니거 아니겠어?'}
tensor([0.9909, 0.0091], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '야 그래도 실력이 있으니 가능한 아니겠어?'}
tensor([0.9902, 0.0098], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '야 그래도 실력이 있으니 가능한거겠어?'}
tensor([0.9875, 0.0125], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9686, 0.0314], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '말빨이 있어서 그런 걸로 좀 휘어잡는 편이야 쟤는.'}
tensor([0.9196, 0.0804], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##이 있어서 그런 걸로 좀 휘어잡는 편이야 쟤는.'}
tensor([0.9663, 0.0337], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '말빨 있어서 그런 걸로 좀 휘어잡는 편이야 쟤는.'}
tensor([0.9518, 0.0482], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '말빨이 그런 걸로 좀 휘어잡는 편이야 쟤는.'}
tensor([0.9556, 0.0444], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '말빨이 있어서 걸로 좀 휘어잡는 편이야 쟤는.'}
tensor([0.9746, 0.0254], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '말빨이 있어서 그런 좀 휘어잡는 편이야 쟤는.'}
tensor([0.9635, 0.0365], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '말빨이 있어서 그런 걸로 휘어잡는 편이야 쟤는.'}
tensor([0.9654, 0.0346], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '말빨이 있어서 그런 걸로 좀어잡는 편이야 쟤는.'}
tensor([0.9658, 0.0342], device='cuda:0', grad_

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9905, 0.0095], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '요새 뭐 자기 PR도 능력인 시대지.'}
tensor([0.9878, 0.0122], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '뭐 자기 PR도 능력인 시대지.'}
tensor([0.9911, 0.0089], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '요새 자기 PR도 능력인 시대지.'}
tensor([0.9870, 0.0130], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '요새 뭐 PR도 능력인 시대지.'}
tensor([0.9883, 0.0117], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '요새 뭐 자기도 능력인 시대지.'}
tensor([0.9931, 0.0069], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '요새 뭐 자기 PR 능력인 시대지.'}
tensor([0.9929, 0.0071], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '요새 뭐 자기 PR도인 시대지.'}
tensor([0.9909, 0.0091], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '요새 뭐 자기 PR도 능력 시대지.'}
tensor([0.9849, 0.0151], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '요새 뭐 자기 PR도 능력인지.'}
te

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.8615, 0.1385], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '쟤 진짜 겉만 번지르르한데 다들 모르네.. 참..'}
tensor([0.8714, 0.1286], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '진짜 겉만 번지르르한데 다들 모르네.. 참..'}
tensor([0.8675, 0.1325], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '쟤 겉만 번지르르한데 다들 모르네.. 참..'}
tensor([0.8990, 0.1010], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '쟤 진짜만 번지르르한데 다들 모르네.. 참..'}
tensor([0.9396, 0.0604], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '쟤 진짜 겉 번지르르한데 다들 모르네.. 참..'}
tensor([0.7289, 0.2711], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '쟤 진짜 겉만한데 다들 모르네.. 참..'}
tensor([0.8333, 0.1667], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '쟤 진짜 겉만 번지르르 다들 모르네.. 참..'}
tensor([0.8010, 0.1990], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '쟤 진짜 겉만 번지르르한데 모르네.. 참..'}
tensor([0.7924, 0.2076], device='cuda:0', grad_fn=<UnbindB

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9718, 0.0282], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '쟤는 음악으로 성공하기가 쉬운줄 아나?'}
tensor([0.9844, 0.0156], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '음악으로 성공하기가 쉬운줄 아나?'}
tensor([0.9304, 0.0696], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '쟤는으로 성공하기가 쉬운줄 아나?'}
tensor([0.9800, 0.0200], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '쟤는 음악 성공하기가 쉬운줄 아나?'}
tensor([0.9597, 0.0403], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '쟤는 음악으로하기가 쉬운줄 아나?'}
tensor([0.9735, 0.0265], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '쟤는 음악으로 성공 쉬운줄 아나?'}
tensor([0.9200, 0.0800], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '쟤는 음악으로 성공하기가줄 아나?'}
tensor([0.9661, 0.0339], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '쟤는 음악으로 성공하기가 쉬운 아나?'}
tensor([0.9699, 0.0301], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '쟤는 음악으로 성공하기가 쉬운

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9924, 0.0076], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '내가 실패하고 싶어서 한 게 아니잖아...'}
tensor([0.9902, 0.0098], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '실패하고 싶어서 한 게 아니잖아...'}
tensor([0.9834, 0.0166], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '내가하고 싶어서 한 게 아니잖아...'}
tensor([0.9917, 0.0083], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '내가 실패 싶어서 한 게 아니잖아...'}
tensor([0.9941, 0.0059], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '내가 실패하고 한 게 아니잖아...'}
tensor([0.9921, 0.0079], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '내가 실패하고 싶어서 게 아니잖아...'}
tensor([0.9922, 0.0078], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '내가 실패하고 싶어서 한 아니잖아...'}
tensor([0.9908, 0.0092], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '내가 실패하고 싶어서 한 게...'}
tensor([0.9914, 0.0086], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '내가 

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.4963, 0.5037], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '의지가 얼마나 없으면 그 모양이냐는 거지...'}
tensor([0.4018, 0.5982], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '얼마나 없으면 그 모양이냐는 거지...'}
tensor([0.8100, 0.1900], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '의지가 없으면 그 모양이냐는 거지...'}
tensor([0.4967, 0.5033], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '의지가 얼마나 그 모양이냐는 거지...'}
tensor([0.6491, 0.3509], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '의지가 얼마나 없으면 모양이냐는 거지...'}
tensor([0.6515, 0.3485], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '의지가 얼마나 없으면 그이냐는 거지...'}
tensor([0.5201, 0.4799], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '의지가 얼마나 없으면 그 모양는 거지...'}
tensor([0.1728, 0.8272], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '의지가 얼마나 없으면 그 모양이냐 거지...'}
tensor([0.4147, 0.5853], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids':

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9931, 0.0069], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '의지의 문제가 아니라 나한테 다이어트는 불가능이야...'}
tensor([0.9859, 0.0141], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##의 문제가 아니라 나한테 다이어트는 불가능이야...'}
tensor([0.9940, 0.0060], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '의지 문제가 아니라 나한테 다이어트는 불가능이야...'}
tensor([0.9930, 0.0070], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '의지의 아니라 나한테 다이어트는 불가능이야...'}
tensor([0.9949, 0.0051], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '의지의 문제가 나한테 다이어트는 불가능이야...'}
tensor([0.9873, 0.0127], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '의지의 문제가 아니라 다이어트는 불가능이야...'}
tensor([0.9862, 0.0138], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '의지의 문제가 아니라 나한테는 불가능이야...'}
tensor([0.9931, 0.0069], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '의지의 문제가 아니라 나한테 다이어트 불가능이야...'}
tensor([0.9932, 0.0068], device='cu

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.5036, 0.4964], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '그렇게 단정짓는 것부터 넌 틀려 먹었어'}
tensor([0.4888, 0.5112], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '단정짓는 것부터 넌 틀려 먹었어'}
tensor([0.3414, 0.6586], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '그렇게짓는 것부터 넌 틀려 먹었어'}
tensor([0.4246, 0.5754], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '그렇게 단정 것부터 넌 틀려 먹었어'}
tensor([0.4857, 0.5143], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '그렇게 단정짓는부터 넌 틀려 먹었어'}
tensor([0.6890, 0.3110], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '그렇게 단정짓는 것 넌 틀려 먹었어'}
tensor([0.8576, 0.1424], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '그렇게 단정짓는 것부터 틀려 먹었어'}
tensor([0.2879, 0.7121], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '그렇게 단정짓는 것부터 넌 먹었어'}
tensor([0.8163, 0.1837], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '그렇게 단정짓는 것부터 넌 틀

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9936, 0.0064], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '저 아줌마 며느리가 아니고 아들이 생일상 차렸다고 열받아서 쓰러졌대'}
tensor([0.9503, 0.0497], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '아줌마 며느리가 아니고 아들이 생일상 차렸다고 열받아서 쓰러졌대'}
tensor([0.9952, 0.0048], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '저 며느리가 아니고 아들이 생일상 차렸다고 열받아서 쓰러졌대'}
tensor([0.9935, 0.0065], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '저 아줌마가 아니고 아들이 생일상 차렸다고 열받아서 쓰러졌대'}
tensor([0.9933, 0.0067], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '저 아줌마 며느리 아니고 아들이 생일상 차렸다고 열받아서 쓰러졌대'}
tensor([0.9968, 0.0032], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '저 아줌마 며느리가 아들이 생일상 차렸다고 열받아서 쓰러졌대'}
tensor([0.9844, 0.0156], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '저 아줌마 며느리가 아니고 생일상 차렸다고 열받아서 쓰러졌대'}
tensor([0.9873, 0.0127], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '저 아줌마 며느리가 아니고 아들이상

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.4414, 0.5586], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '그 며느리 못된 시어메하고 인연끊어라'}
tensor([0.4967, 0.5033], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '며느리 못된 시어메하고 인연끊어라'}
tensor([0.5627, 0.4373], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '그 못된 시어메하고 인연끊어라'}
tensor([0.5067, 0.4933], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '그 며느리 시어메하고 인연끊어라'}
tensor([0.3412, 0.6588], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '그 며느리 못된메하고 인연끊어라'}
tensor([0.6693, 0.3307], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '그 며느리 못된 시어하고 인연끊어라'}
tensor([0.5103, 0.4897], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '그 며느리 못된 시어메 인연끊어라'}
tensor([0.4611, 0.5389], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '그 며느리 못된 시어메하고끊어라'}
tensor([0.4175, 0.5825], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '그 며느리 못된 시어메하고 인연어라'}
te

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9513, 0.0487], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '급식인데 급식소에서 장애 학생 도와줬는데 아무도 몰라줌'}
tensor([0.9493, 0.0507], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##인데 급식소에서 장애 학생 도와줬는데 아무도 몰라줌'}
tensor([0.9235, 0.0765], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '급식 급식소에서 장애 학생 도와줬는데 아무도 몰라줌'}
tensor([0.9539, 0.0461], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '급식인데소에서 장애 학생 도와줬는데 아무도 몰라줌'}
tensor([0.8237, 0.1763], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '급식인데 급식 장애 학생 도와줬는데 아무도 몰라줌'}
tensor([0.9948, 0.0052], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '급식인데 급식소에서 학생 도와줬는데 아무도 몰라줌'}
tensor([0.8512, 0.1488], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '급식인데 급식소에서 장애 도와줬는데 아무도 몰라줌'}
tensor([0.8347, 0.1653], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '급식인데 급식소에서 장애 학생줬는데 아무도 몰라줌'}
tensor([0.8216, 0.1784], device='

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.7924, 0.2076], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '도와달라고 하기 전까지 돕지 마라'}
tensor([0.8069, 0.1931], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##달라고 하기 전까지 돕지 마라'}
tensor([0.8936, 0.1064], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '도와 하기 전까지 돕지 마라'}
tensor([0.7645, 0.2355], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '도와달라고 전까지 돕지 마라'}
tensor([0.8490, 0.1510], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '도와달라고 하기 돕지 마라'}
tensor([0.7970, 0.2030], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '도와달라고 하기 전까지지 마라'}
tensor([0.7802, 0.2198], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '도와달라고 하기 전까지 돕 마라'}
tensor([0.8782, 0.1218], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '도와달라고 하기 전까지 돕지'}
도와달라고 하기 전까지 돕지 마라
Dataset({
    features: ['ids', 'texts'],
    num_rows: 14
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9942, 0.0058], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '죄송해요. 내일부터는 셔츠에 슬랙스 입을게요.'}
tensor([0.9870, 0.0130], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##해요. 내일부터는 셔츠에 슬랙스 입을게요.'}
tensor([0.9931, 0.0069], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '죄송. 내일부터는 셔츠에 슬랙스 입을게요.'}
tensor([0.9943, 0.0057], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '죄송해요 내일부터는 셔츠에 슬랙스 입을게요.'}
tensor([0.9920, 0.0080], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '죄송해요.부터는 셔츠에 슬랙스 입을게요.'}
tensor([0.9954, 0.0046], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '죄송해요. 내일 셔츠에 슬랙스 입을게요.'}
tensor([0.9940, 0.0060], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '죄송해요. 내일부터는에 슬랙스 입을게요.'}
tensor([0.9959, 0.0041], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '죄송해요. 내일부터는 셔츠 슬랙스 입을게요.'}
tensor([0.9953, 0.0047], device='cuda:0', grad_fn=<UnbindBackward0>) 

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9973, 0.0027], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '말을 왜 그렇게 나쁘게 해'}
tensor([0.9963, 0.0037], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '왜 그렇게 나쁘게 해'}
tensor([0.9947, 0.0053], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '말을 그렇게 나쁘게 해'}
tensor([0.9978, 0.0022], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '말을 왜 나쁘게 해'}
tensor([0.9979, 0.0021], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '말을 왜 그렇게 해'}
tensor([0.9954, 0.0046], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '말을 왜 그렇게 나쁘게'}
말을 왜 그렇게 나쁘게 해
Dataset({
    features: ['ids', 'texts'],
    num_rows: 10
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9961, 0.0039], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '그래도 우리 부모님 세대 분들은 좋아하시던데?'}
tensor([0.9965, 0.0035], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '우리 부모님 세대 분들은 좋아하시던데?'}
tensor([0.9962, 0.0038], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '그래도 부모님 세대 분들은 좋아하시던데?'}
tensor([0.9941, 0.0059], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '그래도 우리 세대 분들은 좋아하시던데?'}
tensor([0.9963, 0.0037], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '그래도 우리 부모님 분들은 좋아하시던데?'}
tensor([0.9971, 0.0029], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '그래도 우리 부모님 세대 좋아하시던데?'}
tensor([0.9943, 0.0057], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '그래도 우리 부모님 세대 분들은시던데?'}
tensor([0.9962, 0.0038], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '그래도 우리 부모님 세대 분들은 좋아하던데?'}
tensor([0.9943, 0.0057], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8,

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9958, 0.0042], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '아무리 그래도 그렇지'}
tensor([0.9966, 0.0034], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '그래도 그렇지'}
tensor([0.9969, 0.0031], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '아무리 그렇지'}
tensor([0.9957, 0.0043], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '아무리 그래도'}
아무리 그래도 그렇지
Dataset({
    features: ['ids', 'texts'],
    num_rows: 9
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9109, 0.0891], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '하루종일 트로트만 편성하고 지겨워 죽겠어'}
tensor([0.8836, 0.1164], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '트로트만 편성하고 지겨워 죽겠어'}
tensor([0.9527, 0.0473], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '하루종일만 편성하고 지겨워 죽겠어'}
tensor([0.9340, 0.0660], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '하루종일 트로트 편성하고 지겨워 죽겠어'}
tensor([0.9507, 0.0493], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '하루종일 트로트만하고 지겨워 죽겠어'}
tensor([0.9308, 0.0692], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '하루종일 트로트만 편성 지겨워 죽겠어'}
tensor([0.9765, 0.0235], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '하루종일 트로트만 편성하고 죽겠어'}
tensor([0.9619, 0.0381], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '하루종일 트로트만 편성하고 지겨워겠어'}
tensor([0.7730, 0.2270], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '하루종일 트로트만 편

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9947, 0.0053], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '올해 초부터 원인 모르겠는 어지러움 증상이 생겼는데 생각해보니 집 1km근방에 엄청 큰 송전탑 갑자기 생긴 거 그거 때문인가?'}
tensor([0.9930, 0.0070], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '초부터 원인 모르겠는 어지러움 증상이 생겼는데 생각해보니 집 1km근방에 엄청 큰 송전탑 갑자기 생긴 거 그거 때문인가?'}
tensor([0.9950, 0.0050], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '올해부터 원인 모르겠는 어지러움 증상이 생겼는데 생각해보니 집 1km근방에 엄청 큰 송전탑 갑자기 생긴 거 그거 때문인가?'}
tensor([0.9955, 0.0045], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '올해 초 원인 모르겠는 어지러움 증상이 생겼는데 생각해보니 집 1km근방에 엄청 큰 송전탑 갑자기 생긴 거 그거 때문인가?'}
tensor([0.9946, 0.0054], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '올해 초부터 모르겠는 어지러움 증상이 생겼는데 생각해보니 집 1km근방에 엄청 큰 송전탑 갑자기 생긴 거 그거 때문인가?'}
tensor([0.9939, 0.0061], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '올해 초부터 원인는 어지러움 증상이 생겼는데 생각해보니 집 1km근방에 엄청 큰 송전탑 갑자기 생긴 거 그거 때문인가?'}
tensor([0.9945, 0.0055], device='cud

Exception ignored in: <function tqdm.__del__ at 0x7f25057deef0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1162, in __del__
    self.close()
  File "/usr/local/lib/python3.7/dist-packages/tqdm/notebook.py", line 288, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm' object has no attribute 'disp'


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.3457, 0.6543], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '도찐개찐이지 콩심은데 콩 나는 거고'}
tensor([0.4680, 0.5320], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##이지 콩심은데 콩 나는 거고'}
tensor([0.3690, 0.6310], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '도찐개찐 콩심은데 콩 나는 거고'}
tensor([0.4974, 0.5026], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '도찐개찐이지심은데 콩 나는 거고'}
tensor([0.4229, 0.5771], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '도찐개찐이지 콩데 콩 나는 거고'}
tensor([0.4256, 0.5744], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '도찐개찐이지 콩심은 콩 나는 거고'}
tensor([0.4287, 0.5713], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '도찐개찐이지 콩심은데 나는 거고'}
tensor([0.3368, 0.6632], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '도찐개찐이지 콩심은데 콩 거고'}
tensor([0.3590, 0.6410], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '도찐개찐이지 콩심은데 콩 나는'}
도찐개찐이지 콩심

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9971, 0.0029], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '오토바이 배달원이 억울하게 가해자로 몰려서 배상해줘야한대'}
tensor([0.9965, 0.0035], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '배달원이 억울하게 가해자로 몰려서 배상해줘야한대'}
tensor([0.9960, 0.0040], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '오토바이원이 억울하게 가해자로 몰려서 배상해줘야한대'}
tensor([0.9959, 0.0041], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '오토바이 배달 억울하게 가해자로 몰려서 배상해줘야한대'}
tensor([0.9966, 0.0034], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '오토바이 배달원이 가해자로 몰려서 배상해줘야한대'}
tensor([0.9964, 0.0036], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '오토바이 배달원이 억울하게로 몰려서 배상해줘야한대'}
tensor([0.9967, 0.0033], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '오토바이 배달원이 억울하게 가해자 몰려서 배상해줘야한대'}
tensor([0.9966, 0.0034], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '오토바이 배달원이 억울하게 가해자로서 배상해줘야한대'}
tensor([0.9969, 0.0031], device

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9953, 0.0047], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '오토바이 시동 꺼진걸 다른 사람이 건드려서 시동이 걸린거야'}
tensor([0.9937, 0.0063], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '시동 꺼진걸 다른 사람이 건드려서 시동이 걸린거야'}
tensor([0.9949, 0.0051], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '오토바이 꺼진걸 다른 사람이 건드려서 시동이 걸린거야'}
tensor([0.9940, 0.0060], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '오토바이 시동진걸 다른 사람이 건드려서 시동이 걸린거야'}
tensor([0.9935, 0.0065], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '오토바이 시동 꺼걸 다른 사람이 건드려서 시동이 걸린거야'}
tensor([0.9924, 0.0076], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '오토바이 시동 꺼진 다른 사람이 건드려서 시동이 걸린거야'}
tensor([0.9948, 0.0052], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '오토바이 시동 꺼진걸 사람이 건드려서 시동이 걸린거야'}
tensor([0.9899, 0.0101], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '오토바이 시동 꺼진걸 다른 건드려서 시동이 걸린거야'}
tensor([0.9918, 0.0

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9289, 0.0711], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '가난은 단지 조금 불편한 것 뿐이야'}
tensor([0.9796, 0.0204], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '##은 단지 조금 불편한 것 뿐이야'}
tensor([0.9115, 0.0885], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '가난 단지 조금 불편한 것 뿐이야'}
tensor([0.9464, 0.0536], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '가난은 조금 불편한 것 뿐이야'}
tensor([0.9147, 0.0853], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '가난은 단지 불편한 것 뿐이야'}
tensor([0.9188, 0.0812], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '가난은 단지 조금 것 뿐이야'}
tensor([0.9639, 0.0361], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '가난은 단지 조금 불편한 뿐이야'}
tensor([0.9793, 0.0207], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '가난은 단지 조금 불편한 것'}
가난은 단지 조금 불편한 것 뿐이야
Dataset({
    features: ['ids', 'texts'],
    num_rows: 8
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9790, 0.0210], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '[UNK] 2030 표심 잡으려고 움직이네.'}
tensor([0.9871, 0.0129], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '2030 표심 잡으려고 움직이네.'}
tensor([0.9352, 0.0648], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '[UNK] 표심 잡으려고 움직이네.'}
tensor([0.9776, 0.0224], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '[UNK] 2030 잡으려고 움직이네.'}
tensor([0.9931, 0.0069], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '[UNK] 2030 표심 움직이네.'}
tensor([0.9256, 0.0744], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '[UNK] 2030 표심 잡으려고네.'}
tensor([0.9718, 0.0282], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '[UNK] 2030 표심 잡으려고 움직이.'}
tensor([0.9790, 0.0210], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '[UNK] 2030 표심 잡으려고 움직이네'}
[UNK] 2030 표심 잡으려고 움직이네.
Dataset({
    features: ['ids', 'texts'],
    num_rows: 9
})


  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9959, 0.0041], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '은근 젊은 층 중에 [UNK] 지지자들 많음.'}
tensor([0.9944, 0.0056], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '젊은 층 중에 [UNK] 지지자들 많음.'}
tensor([0.9936, 0.0064], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '은근 층 중에 [UNK] 지지자들 많음.'}
tensor([0.9955, 0.0045], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '은근 젊은 중에 [UNK] 지지자들 많음.'}
tensor([0.9964, 0.0036], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '은근 젊은 층 [UNK] 지지자들 많음.'}
tensor([0.9967, 0.0033], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '은근 젊은 층 중에 지지자들 많음.'}
tensor([0.9842, 0.0158], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '은근 젊은 층 중에 [UNK] 많음.'}
tensor([0.9919, 0.0081], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '은근 젊은 층 중에 [UNK] 지지자들.'}
tensor([0.9959, 0.0041], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, '

  0%|          | 0/1 [00:00<?, ?ba/s]

tensor([0.9944, 0.0056], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 0, 'texts': '맞아. 카리스마 있는 리더처럼 느껴져.'}
tensor([0.9947, 0.0053], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 1, 'texts': '. 카리스마 있는 리더처럼 느껴져.'}
tensor([0.9947, 0.0053], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 2, 'texts': '맞아 카리스마 있는 리더처럼 느껴져.'}
tensor([0.9897, 0.0103], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 3, 'texts': '맞아. 있는 리더처럼 느껴져.'}
tensor([0.9933, 0.0067], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 4, 'texts': '맞아. 카리스마 리더처럼 느껴져.'}
tensor([0.9933, 0.0067], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 5, 'texts': '맞아. 카리스마 있는처럼 느껴져.'}
tensor([0.9943, 0.0057], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 6, 'texts': '맞아. 카리스마 있는 리더 느껴져.'}
tensor([0.9877, 0.0123], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 7, 'texts': '맞아. 카리스마 있는 리더처럼.'}
tensor([0.9937, 0.0063], device='cuda:0', grad_fn=<UnbindBackward0>) {'ids': 8, 'texts': '맞아. 카리스마 있는 리더처럼 느

KeyboardInterrupt: ignored

In [ ]:
train_tokenized_datasets

## make train dataset

## train with sweep

In [ ]:
sweep_configuration = {
    'method': 'grid',
    'name': 'sweep',
    'metric': {'goal': 'minimize', 'name': 'eval/loss'},
    'parameters': 
    {
        'batch_size': {'values': [256]},
        'epochs': {'values': [5]},
        'lr': {'values': [1e-5]},
        'scheduler': {'values': ['linear', 'cosine', 'constant']}
     }
}

In [ ]:
max_batch_size = 256
def train():
    torch.cuda.empty_cache()
    model = AutoModelForSequenceClassification.from_pretrained(model_name)
    grouped_params = model.parameters()
    run = wandb.init(config=sweep_configuration, entity="groom2team")
    batch_size = wandb.config.batch_size if wandb.config.batch_size < max_batch_size else max_batch_size
    gradient_accumulation_steps= wandb.config.batch_size // max_batch_size
    epochs = wandb.config.epochs
    total_steps = int(len(train_tokenized_datasets)/wandb.config.batch_size*epochs)
    learning_rate = wandb.config.lr
    data_collator = default_data_collator
    grouped_params = model.parameters()
    optimizer=AdamW(grouped_params, lr=learning_rate)
    scheduler_type = wandb.config.scheduler
    if scheduler_type == 'linear':
        scheduler = get_linear_schedule_with_warmup(optimizer=optimizer,
                                                    num_warmup_steps=0,
                                                    num_training_steps=total_steps+1)
    elif scheduler_type == 'cosine':
        scheduler=get_cosine_schedule_with_warmup(optimizer=optimizer,
                                            num_warmup_steps=0,
                                            num_training_steps=total_steps+1)
    elif scheduler_type == 'constant':
        scheduler=get_constant_schedule(optimizer=optimizer)
    optimizers = optimizer, scheduler
    args = TrainingArguments(
        f"{model_name}-finetuned",
        evaluation_strategy = "steps",
        learning_rate=learning_rate,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=epochs,
        gradient_accumulation_steps = gradient_accumulation_steps,
        report_to="wandb",
        run_name="utopia",
        logging_steps = total_steps//200,
        eval_steps = total_steps//100,
        save_steps = total_steps//100,
        weight_decay=0.0,
        save_total_limit = 2,
        load_best_model_at_end=True
    )
    trainer = Trainer(
        model,
        args,
        train_dataset=train_tokenized_datasets,
        eval_dataset=dev_tokenized_datasets,
        data_collator=data_collator,
        tokenizer=tokenizer,
        callbacks = [EarlyStoppingCallback(early_stopping_patience=10)],
        optimizers=optimizers
    )
    trainer.train()# train 하고
    trainer.save_model(output_dir= 'pytorch_finetuned') # trainer에서 실행된 model save
    artifact = wandb.Artifact(name='pytorch_finetuned', type='model') # wandb에 해당 모델 version 관리.
    artifact.add_dir('pytorch_finetuned', name='best_model_at_end')
    run.log_artifact(artifact)

In [ ]:
sweep_id = wandb.sweep(sweep=sweep_configuration, project='pj3_class_kcelectra', entity='groom2team')
count = 3

Create sweep with ID: eacjzlg5
Sweep URL: https://wandb.ai/groom2team/pj3_class_kcelectra/sweeps/eacjzlg5


In [ ]:
wandb.agent(sweep_id, function=train, count=count)

wandb: Agent Starting Run: lrcyhiso with config:
wandb: 	batch_size: 256
wandb: 	epochs: 5
wandb: 	lr: 5e-05
wandb: 	scheduler: linear


Downloading:   0%|          | 0.00/511M [00:00<?, ?B/s]

Some weights of the model checkpoint at beomi/KcELECTRA-base-v2022 were not used when initializing ElectraForSequenceClassification: ['discriminator_predictions.dense.bias', 'discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense.weight', 'discriminator_predictions.dense_prediction.weight']
- This IS expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ElectraForSequenceClassification were not initialized from the model checkpoint at beomi/KcELECTRA-base-v2022 and are newly initialized: ['classifier.dense.bias', 'c

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
***** Running training *****
  Num examples = 236856
  Num Epochs = 5
  Instantaneous batch size per device = 256
  Total train batch size (w. parallel, distributed & accumulation) = 256
  Gradient Accumulation steps = 1
  Total optimization steps = 4630
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"


***** Running Evaluation *****
  Num examples = 59215
  Batch size = 256
Saving model checkpoint to beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46
Configuration saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/config.json
Model weights saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/pytorch_model.bin
tokenizer config file saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/tokenizer_config.json
Special tokens file saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/special_tokens_map.json
***** Running Evaluation *****
  Num examples = 59215
  Batch size = 256
Saving model checkpoint to beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92
Configuration saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92/config.json
Model weights saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92/pytorch_model.bin
tokenizer config file saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92/tokenizer_config.json
Special tokens file saved in b

wandb: Agent Starting Run: cviu6aju with config:
wandb: 	batch_size: 256
wandb: 	epochs: 5
wandb: 	lr: 5e-05
wandb: 	scheduler: cosine
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--beomi--KcELECTRA-base-v2022/snapshots/4431b6c7ad00f82fd50880864574cef97e0a368b/config.json
Model config ElectraConfig {
  "_name_or_path": "beomi/KcELECTRA-base-v2022",
  "architectures": [
    "ElectraForPreTraining"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "embedding_size": 768,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "electra",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "summary_activation": "gelu",
  "summary_last_dropout": 0.1,
  "summary_type": "first",
  "summary_use_proj": true,


/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
PyTorch: setting up devices
***** Running training *****
  Num examples = 236856
  Num Epochs = 5
  Instantaneous batch size per device = 256
  Total train batch size (w. parallel, distributed & accumulation) = 256
  Gradient Accumulation steps = 1
  Total optimization steps = 4630
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"


***** Running Evaluation *****
  Num examples = 59215
  Batch size = 256
Saving model checkpoint to beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46
Configuration saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/config.json
Model weights saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/pytorch_model.bin
tokenizer config file saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/tokenizer_config.json
Special tokens file saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/special_tokens_map.json
Deleting older checkpoint [beomi/KcELECTRA-base-v2022-finetuned/checkpoint-828] due to args.save_total_limit
***** Running Evaluation *****
  Num examples = 59215
  Batch size = 256
Saving model checkpoint to beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92
Configuration saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92/config.json
Model weights saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92/pytorch_model.bin
tokenizer config file sav

wandb: Agent Starting Run: y75qh4ca with config:
wandb: 	batch_size: 256
wandb: 	epochs: 5
wandb: 	lr: 5e-05
wandb: 	scheduler: constant
loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--beomi--KcELECTRA-base-v2022/snapshots/4431b6c7ad00f82fd50880864574cef97e0a368b/config.json
Model config ElectraConfig {
  "_name_or_path": "beomi/KcELECTRA-base-v2022",
  "architectures": [
    "ElectraForPreTraining"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "embedding_size": 768,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "electra",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "summary_activation": "gelu",
  "summary_last_dropout": 0.1,
  "summary_type": "first",
  "summary_use_proj": true

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,
PyTorch: setting up devices
***** Running training *****
  Num examples = 236856
  Num Epochs = 5
  Instantaneous batch size per device = 256
  Total train batch size (w. parallel, distributed & accumulation) = 256
  Gradient Accumulation steps = 1
  Total optimization steps = 4630
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"


***** Running Evaluation *****
  Num examples = 59215
  Batch size = 256
Saving model checkpoint to beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46
Configuration saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/config.json
Model weights saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/pytorch_model.bin
tokenizer config file saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/tokenizer_config.json
Special tokens file saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-46/special_tokens_map.json
Deleting older checkpoint [beomi/KcELECTRA-base-v2022-finetuned/checkpoint-828] due to args.save_total_limit
***** Running Evaluation *****
  Num examples = 59215
  Batch size = 256
Saving model checkpoint to beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92
Configuration saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92/config.json
Model weights saved in beomi/KcELECTRA-base-v2022-finetuned/checkpoint-92/pytorch_model.bin
tokenizer config file sav

In [ ]:
wandb.finish() # wandb 종료